---

    - name: postgres | import postgres signing key
      apt_key:
        url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
        state: present

    - name: postgres | add source for postgres to apt repository
      apt_repository:
          repo: 'deb http://apt.postgresql.org/pub/repos/apt {{ ansible_distribution_release }}-pgdg main'
          update_cache: yes
          state: present

    - name: postgres | update pkg list
      apt:
        update_cache: yes
        upgrade: dist

    - name: postgres | install postgres
      apt:
        name: "{{ item }}"
        state: installed
      with_items:
        - postgresql-{{ postgres_version }}
        - postgresql-contrib-{{ postgres_version }}
        - python-psycopg2

    - name: postgres | ensure service is running
      service:
        name: postgresql
        state: started
        enabled: yes

    - name: postgres | listen to all addresses
      replace:
        path: /etc/postgresql/{{ postgres_version }}/main/postgresql.conf
        regexp: ".*listen_addresses.*"
        replace: "listen_addresses = '*'"
      notify:
         - restart postgres

    - name: postgres | add password auth
      lineinfile:
        path: /etc/postgresql/{{ postgres_version }}/main/pg_hba.conf
        line: "host    all             all             all            md5"
      notify:
         - restart postgres

    - name: postgres | explicitly set default client encoding
      lineinfile:
        path: /etc/postgresql/{{ postgres_version }}/main/postgresql.conf
        line: "client_encoding = utf8"
      notify:
         - restart postgres

    - name: db | create database user
      become_user: postgres
      postgresql_user:
        name: "{{ service_db_user }}"
        password: "{{ service_db_password }}"

    - name: db | create service database
      become_user: postgres
      postgresql_db:
        name: "{{ service_db_name }}"
        encoding: UTF-8
        lc_collate: en_US.utf8
        lc_ctype: en_US.utf8
        template: template0
        owner: "{{ service_db_user }}"

