---

    - name: create venv for service
      become_user: "{{ service_user }}"
      shell: "virtualenv -p $(which python{{ python_version }}) {{ service_venv_dir }}"
      args:
        creates: "{{ service_venv_dir }}"
