---
    - name: nginx configuration file
      template:
        src: "service_config.j2"
        dest: /etc/nginx/sites-available/{{ with_ssl is True | ternary('', 'nonssl_') }}{{ service_name }}
        backup: yes


