---
    - name: copy ssl cert to service host
      copy:
        src: "{{ local_certs_dir }}/{{ item }}_{{ service_name }}_harvardx_harvard_edu.crt"
        dest: "{{ nginx_ssl_dest_dir }}/{{ item }}_{{ service_name }}_harvardx_harvard_edu.crt"
        mode: 0644
      with_items: "{{ cert_prefix_list }}"

    - name: copy ssl private_key to service host
      copy:
        src: "{{ local_certs_dir }}/{{ item }}_{{ service_name }}_harvardx_harvard_edu.key"
        dest: "{{ nginx_ssl_dest_dir }}/{{ item }}_{{ service_name }}_harvardx_harvard_edu.key"
        mode: 0600
      with_items: "{{ cert_prefix_list }}"

