---
    - name: copy ssl cert to service host
      copy:
        src: "{{ playbook_dir }}/vars/{{ service_name }}_harvardx_harvard_edu_bundle.crt"
        dest: "{{ nginx_ssl_dest_dir }}/{{ service_name }}_harvardx_harvard_edu.crt"
        mode: 0644
      notify: restart nginx
      tags:
        - certs

    - name: copy ssl private key to service host
      copy:
        src: "{{ playbook_dir }}/vars/{{ service_name }}_harvardx_harvard_edu.key"
        dest: "{{ nginx_ssl_dest_dir }}/{{ service_name }}_harvardx_harvard_edu.key"
        mode: 0600
      notify: restart nginx
      tags:
        - certs

