---
    - name: copy ssl cert dir to service host
      copy:
        src: "{{ item }}"
        dest: "{{ nginx_ssl_dest_dir }}/{{ item | basename }}"
        mode: 0644
      with_fileglob:
        - "{{ local_certs_dir }}/*.crt"

    - name: copy ssl private_key to service host
      copy:
        src: "{{ item }}"
        dest: "{{ nginx_ssl_dest_dir }}/{{ item | basename }}"
        mode: 0600
      with_fileglob:
        - "{{ local_certs_dir }}/*.key"

