---
    - name: install nginx
      apt:
        name: nginx
        state: installed

    - name: copy ssl cert to service host
      copy:
        content: "{{ ssl_crt }}"
        dest: "{{ nginx_ssl_dest_dir }}/{{ service_name }}.crt"
      notify: restart nginx
      tags:
        - certs

    - name: copy ssl private key to service host
      copy:
        content: "{{ ssl_key }}"
        dest: "{{ nginx_ssl_dest_dir }}/{{ service_name }}.key"
      notify: restart nginx
      tags:
        - certs

    - name: nginx socket tuning | worker_connections
      lineinfile:
        path: /etc/nginx/nginx.conf
        regexp: '^(.*)worker_connections'
        line: '\1worker_connections 2048;'
        backrefs: yes
        state: present
        backup: yes
      notify: restart nginx
      tags:
        - socket_tunning

    - name: nginx socket tuning | proxy_connect_timeout
      lineinfile:
        path: /etc/nginx/nginx.conf
        regexp: '( *)proxy_connect_timeout'
        line: 'proxy_connect_timeout 300s;'
        state: present
        insertafter: '^(.*)default_type application\/octet-stream;'
        backup: yes
      notify: restart nginx
      tags:
        - socket_tunning

    - name: nginx socket tuning | proxy_read_timeout
      lineinfile:
        path: /etc/nginx/nginx.conf
        regexp: '( *)proxy_read_timeout'
        line: 'proxy_read_timeout 300s;'
        state: present
        insertafter: '^(.*)default_type application\/octet-stream;'
        backup: yes
      notify: restart nginx
      tags:
        - socket_tunning

    - name: nginx configuration file
      template:
        src: "service_config.j2"
        dest: /etc/nginx/sites-available/{{ service_name }}
        backup: yes
      notify: restart nginx
      tags:
        - nginx_config

    - name: ensure default site is disabled
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: restart nginx

    - name: ensure service site is enabled
      file:
        src: /etc/nginx/sites-available/{{ service_name }}
        dest: /etc/nginx/sites-enabled/{{ service_name }}
        state: link
      notify: restart nginx

