---

    # can only run this after env is configured!
    - name: django_manage | apply migrations
      become_user: "{{ service_user }}"
      environment:
        CATCHPY_DOTENV_PATH: "{{ service_dotenv_path }}"
      django_manage:
        command: migrate
        app_path: "{{ service_install_dir }}"
        virtualenv: "{{ service_venv_dir }}"

    - name: django_manage | run collectstatic
      become_user: "{{ service_user }}"
      environment:
        CATCHPY_DOTENV_PATH: "{{ service_dotenv_path }}"
      django_manage:
        command: collectstatic
        app_path: "{{ service_install_dir }}"
        virtualenv: "{{ service_venv_dir }}"
      notify: restart webapp

