---
    # webapp_role depends or either webapp_install or webapp_deploy

    # https://www.digitalocean.com/community/tutorials/how-to-set-up-django-with-postgres-nginx-and-gunicorn-on-ubuntu-16-04
    - include: dotenv.yml
    - include: django_manage.yml


