---

    # https://www.digitalocean.com/community/tutorials/how-to-set-up-django-with-postgres-nginx-and-gunicorn-on-ubuntu-16-04
    - name: cfg | pull .env template from provisioned host
      fetch:
        src: "{{ service_dotenv_template_path }}"
        dest: "/tmp"
        fail_on_missing: yes

    - name: cfg | drop .env file
        template:
          src: "/tmp/{{ inventory_hostname }}/{{ service_dotenv_template_filename }}"
          dest: "{{ service_dotenv_path }}"
          owner: "{{ service_user }}"
          group: "{{ service_user }}"
          mode: 0744

    # can only run this after env is configured!
    - name: cfg | apply migrations
      django_manage:
        command: migrate
        app_path: "{{ service_install_dir }}"
        virtualenv: "{{ service_venv_dir }}"

