# initial playbook to provision a catchpy server
---

- hosts: all
  remote_user: vagrant
  become: yes
  vars:
    service_name: catchpy
    service_user: "{{ service_name }}"
    service_user_home: "/home/{{ service_user }}"
    service_git_repo: "https://github.com/nmaekawa/catch.git"
    service_git_revision: "api-doc"

  handlers:
    - include: handlers.yml

  roles:
    - apt
    - timedate

    -
      role: user_account
      user_account: "{{ service_user }}"
      user_account_home: "{{ service_user_home }}"


- hosts: catchpy
  remote_user: vagrant
  become: yes
  vars:
    service_name: catchpy
    service_user: "{{ service_name }}"
    service_user_home: "/home/{{ service_user }}"
    service_git_repo: "https://github.com/nmaekawa/catch.git"
    service_git_revision: "api-doc"

  roles:

    - python_setup

    -
      role: python_venv
      user: "{{ service_user }}"
      python_version: 3
      venv_dir: "{{ service_user_home }}/.venvs"
      venv_name: "{{ service_name }}"

    -
      role: catchpy_install
      catchpy_user: "{{ service_user }}"
      catchpy_install_dir: "{{ service_user_home }}/{{ service_name }}"
      catchpy_git_repo: "{{ service_git_repo }}"
      catchpy_git_revision: "{{ service_git_revision }}"
      catchpy_venv_dir: "{{ catchpy_install_dir }}/.venv"





