# initial playbook to provision a catchpy server
---

- hosts: all
  remote_user: vagrant
  become: yes
  become_user: root
  vars_files:
    - vars/catchpy_vars.yml

  handlers:
    - include: handlers/handlers.yml

  roles:
    - apt
    - timedate
    - python_setup

    - user_account


- hosts: postgres
  remote_user: vagrant
  become: yes
  become_user: root
  vars_files:
    - vars/catchpy_vars.yml

  handlers:
    - include: handlers/handlers.yml

  roles:
    - postgresql


- hosts: catchpy
  remote_user: vagrant
  become: yes
  become_user: root
  vars_files:
    - vars/catchpy_vars.yml

  handlers:
    - include: handlers/handlers.yml

  roles:
    - nginx
    - python_venv
    - webapp_install
    -
      role: webapp_config
      webapp_name: "{{ service_name }}"
      webapp_install_dir: "{{ service_install_dir }}"
      webapp_venv_dir: "{{ service_venv_dir }}"
      webapp_settings: "{{ service_settings }}"
      webapp_dotenv_template_path:
      webapp_dotenv_template_filename:
      tags:
        - run_now
