# initial playbook to provision a catchpy server
---
- hosts: all
  remote_user: "{{ remote_user }}"
  become: yes
  become_user: root
  gather_facts: False

  tasks:
  - name: install python2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)


- hosts: all
  remote_user: "{{ remote_user }}"
  become: yes
  become_user: root
  vars_files:
    - vars/catchpy_vars.yml
    - vars/catchpy_aws_vars.yml
    - vars/users_public_keys.yml

  handlers:
    - include: handlers/handlers.yml

  tasks:
    - import_role: apt
    - import_role: timedate
    - import_role: python_setup
    - import_role: user_account
    - import_tasks: roles/aws/tasks/setup_ebs_volumes.yml
      when: aws is defined and aws == true
