# initial playbook to provision a catchpy server
---
- hosts: all
  remote_user: "{{ remote_user }}"
  become: yes
  become_user: root
  gather_facts: False

  tasks:
  - name: install python2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)


- hosts: all
  remote_user: "{{ remote_user }}"
  become: yes
  become_user: root
  vars_files:
    - vars/catchpy_vars.yml
    - vars/users_public_keys.yml

  handlers:
    - include: handlers/handlers.yml

  roles:
    - apt
    - timedate
    - python_setup
    - user_account
    - aws




