
---

    - name: create user_account group
      group:
        name: "{{ service_user }}"
        state: present

    - name: create service_user
      user:
        name: "{{ service_user }}"
        group: "{{ service_user }}"
        home: "{{ service_user_home }}"
        state: present

    - name: create service rootdir
      file:
        path: "{{ service_rootdir }}"
        owner: "{{ service_user }}"
        group: "{{ service_user }}"
        mode: 0775
        state: directory
