---


    - include: setup_user.yml user={{ item }}
      with_items:
        - "{{ devo_users }}"
      tags:
        - create_users


    - include: setup_user.yml
      args:
        user:
            name: "{{ service_user }}"
            group: "{{ service_group }}"
      tags:
        - create_users

