---

    - name: gunicorn | install gunicorn in webapp venv
      become_user: "{{ service_user }}"
      pip:
        virtualenv: "{{ service_venv_dir }}"
        chdir: "{{ service_install_dir }}"
        name: gunicorn
        state: present

    - name: gunicorn | create gunicorn config
      become_user: "{{ service_user }}"
      template:
        src: gunicorn_start.j2
        dest: "{{ service_venv_dir }}/bin/gunicorn_start"
        owner: "{{ service_user }}"
        group: "{{ service_group }}"
        mode: 0755
        backup: yes

    - name: supervisor | ensure supervisor is running
      service:
        name: supervisor
        state: started
        enabled: yes

    - name: supervisor | create supervisor config
      template:
        src: supervisor_config.j2
        dest: /etc/supervisor/conf.d/{{ service_name }}.conf
        backup: yes

    - name: supervisor | reload supervisor config for {{ service_name }}
      supervisorctl:
        name: "{{ service_name }}"
        state: present

