---

    - name: setup | clone service repo
      become_user: "{{ service_user }}"
      git:
        repo: "{{ service_git_repo }}"
        dest: "{{ service_install_dir }}"
        version: "{{ service_git_revision }}"
        accept_hostkey: yes

    - name: setup | install requirements
      become_user: "{{ service_user }}"
      pip:
        virtualenv: "{{ service_venv_dir }}"
        chdir: "{{ service_install_dir }}"
        requirements: "./requirements.txt"
        state: present

    - name: setup | pip install service package
      become_user: "{{ service_user }}"
      shell: ". {{ service_venv_dir }}/bin/activate && pip install -e ."
      args:
        chdir: "{{ service_install_dir }}"

    - name: setup | add CATCHPY_DOTENV_PATH to .bashrc
      become_user: "{{ service_user }}"
      lineinfile:
        path: /home/{{ service_user }}/.bashrc
        line: "export {{ service_name | upper }}_DOTENV_PATH={{ service_dotenv_path }}"
        backup: yes
        state: present

    - name: setup | install postgres client
      apt:
        name: postgresql-client
        state: present
