---
    - include_tasks: create_dirs.yml
    - include_tasks: install.yml
    - include_tasks: pip_requirements.yml
    - include_tasks: dotenv_path.yml
    - include_tasks: gunicorn.yml

    - include_tasks: socket_tuning.yml
      when: use_aws

    - name: install postgres client
      apt:
        name: postgresql-client
        state: present


