---
    - include: create_dirs.yml
    - include: install.yml
    - include: pip_requirements.yml
    - include: dotenv_path.yml
    - include: gunicorn.yml
    - include: socket_tuning.yml

    - name: install postgres client
      apt:
        name: postgresql-client
        state: present


