---

    - name: setup | clone service repo
      become_user: "{{ service_user }}"
      git:
        repo: "{{ service_git_repo }}"
        dest: "{{ service_install_dir }}"
        version: "{{ service_git_revision }}"
        accept_hostkey: yes

    - name: setup | install requirements
      become_user: "{{ service_user }}"
      pip:
        virtualenv: "{{ service_venv_dir }}"
        chdir: "{{ service_install_dir }}"
        requirements: "./requirements.txt"
        state: present

