---

    - name: install service requirements
      become_user: "{{ service_user }}"
      pip:
        virtualenv: "{{ service_venv_dir }}"
        chdir: "{{ service_install_dir }}"
        requirements: "./requirements.txt"
        state: present

    - name: pip install service package
      become_user: "{{ service_user }}"
      shell: ". {{ service_venv_dir }}/bin/activate && pip install -e ."
      args:
        chdir: "{{ service_install_dir }}"


