---

    - name: setup | clone catchpy repo
      become_user: "{{ catchpy_user }}"
      git:
        repo: "{{ catchpy_git_repo }}"
        dest: "{{ catchpy_install_dir }}"
        version: "{{ catchpy_git_revision }}"
        accept_hostkey: yes

    - name: setup | install requirements
      become_user: "{{ catchpy_user }}"
      pip:
        virtualenv: "{{ catchpy_venv_dir }}"
        chdir: "{{ catchpy_install_dir }}"
        requirements: "./requirements.txt"
        state: present

