---

    - name: copy scripts
      template:
        src: "{{ item }}"
        dest: "{{ hx_rootdir }}/bin/{{ item | basename }}"
        owner: "root"
        group: "root"
        mode: "0775"
      with_fileglob:
        - "../templates/*"
