---

    - name: create instance profile
      become: no
      local_action: |
        shell {{ role_path }}/files/create_instance_profile.sh \
        {{ lookup('env', 'AWS_PROFILE') }} \
        file:/{{ role_path }}/files/cloudwatch_put_metric_policy.json \
        {{ permission_name }}
      register: policy_result

    - debug:
        var: policy_result

    - name: associate instance profile to instance
      become: no
      local_action: |
          shell aws ec2 associate-iam-instance-profile \
          --instance-id {{ ansible_ec2_instance_id }} \
          --iam-instance-profile Name={{ permission_name }}_instance_profile
