---

    - name: ensure hx global bin folder
      file:
        path: "{{ org_rootdir }}/bin"
        owner: "root"
        group: "root"
        mode: 0755
        state: directory

    - name: ensure tmp global bin folder
      file:
        path: "{{ org_rootdir }}/tmp"
        owner: "root"
        group: "root"
        mode: 0755
        state: directory

