---
    - include_tasks: set_instance_facts.yml
    - include_tasks: setup_iam_instance_profile.yml
    #- include_tasks: test_associations.yml permission_name=ec2_cloudwatch_put_read_list


      #- include: create_cloudwatch_user.yml
      #- include: create_dirs
      #- include: copy_metric_scripts.yml
      #- include: set_cronjobs.yml

